In [1]:
import pandas as pd

## createing a datafram using pandas

In [4]:
# dataframe for the students
df = pd.DataFrame({ 
    "Name": [
        "Nishidh Singh",
        "Mark Holzarator",
        "Charris"
    ],
    "cgpa": [8, 8.3, 9],
    "iq": [123, 144, 132]
})

In [10]:
df

              Name  cgpa   iq
0    Nishidh Singh   8.0  123
1  Mark Holzarator   8.3  144
2          Charris   9.0  132

In [8]:
iq = pd.Series([123, 144, 132], name="iq")

In [9]:
iq

0    123
1    144
2    132
Name: iq, dtype: int64

In [11]:
iq.max()

np.int64(144)

In [12]:
iq.describe()

count      3.000000
mean     133.000000
std       10.535654
min      123.000000
25%      127.500000
50%      132.000000
75%      138.000000
max      144.000000
Name: iq, dtype: float64

In [14]:
df.describe()

           cgpa          iq
count  3.000000    3.000000
mean   8.433333  133.000000
std    0.513160   10.535654
min    8.000000  123.000000
25%    8.150000  127.500000
50%    8.300000  132.000000
75%    8.650000  138.000000
max    9.000000  144.000000

In [15]:
iq.std()

np.float64(10.535653752852738)

In [16]:
iq.quantile()

np.float64(132.0)